### ISSUE TITLE
Qestion: Which kernel implements VPU_IOC_WRITE ioctl?

### ISSUE THREAD

**Issue by santo4ul** [HermanChen/mpp#10]
Hi,

Which kernel implements the VPU_IOC_WRITE ioctl that is being used in this library. 

I couldn't find it in the rockchip-linux/kernel (tried different branches). 

Could someone throw some light? 

Thanks,
San

**Comment by HermanChen** [comment]
It is better to ask this question here:
https://github.com/rockchip-linux/mpp
This is my personal develop repo.

**Comment by santo4ul** [comment]
Thanks Chen!
