### ISSUE TITLE
如何支持 H264 constrainedbaseline profile?

### ISSUE THREAD

**Issue by caryluck** [HermanChen/mpp#16]
android端解码profile-leve-id是42e01f，用的是constrainedbaseline h264，请问mpp编码如何设置支持42e01f的profile-level_id？

**Comment by HermanChen** [comment]
0x42 为 66，即 baseline
level id 中的 e01f 是什么含义不太清楚，需要具体看下代码中是怎么定义的
如果是 constrained baseline 定义的话，要求 profile 是 66，然后 constraint_set0_flag, constraint_set1_flag 配置为 1，level 为需要的正常 level 值即可，这部分可以在 H264e_sps.c 文件中进行修改
