### ISSUE TITLE
Using smart GOP

### ISSUE THREAD

**Issue by jpiat** [HermanChen/mpp#20]
HI,

i'm trying to enable smart GOP but cannot find how to do so. It seems that setting the gop_mode to 4 should enable this feature but then what should be the values of gop_len and vi_len ? Where is this feature documented ?

Thanks

**Comment by HermanChen** [comment]
The smart GOP is a kind of reference frame hierachy config.
gop_len defined the frame number between two IDR frame.
vi_len defined frame number between two longterm reference frame the VI frame is a inter frame and reference to previous long-term reference frame.
gop_len is better to be multiple of vi_len and vi_len is better to be multiple of fps.
