### ISSUE TITLE
mpp_log not print

### ISSUE THREAD

**Issue by susfly** [HermanChen/mpp#26]
hardware: RK3328-PC
os: Android 7.1
problem:   all of the mpp_log  mpp_err can not print,  no log output.

so I have to change 
```
#ifdef mpp_err
#undef mpp_err
#endif
#define mpp_err printf

#ifdef mpp_log
#undef mpp_log
#endif
#define mpp_log printf
```
and the printf can print success.

how should I use mpp_log?

**Comment by HermanChen** [comment]
Android or Linux kernel?
