### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by Nybon** [HermanChen/mpp#28]
Hello.

I'm building mpp into a Qt program and facing difficulties while importing the necessary header files. I'm building my program on a Linux distribution and the media library struggles to find header files located in other folders of the library. 

Here is a picture illustrating what I am talking about. 
![GithubPNG](https://user-images.githubusercontent.com/64807403/99126081-bea35800-2605-11eb-88d1-8025ac7aca69.PNG)
 My code finds every header file, but the header files can't find other header files that are not located in the same folder. As shown in the picture, _mpp-develop\mpp\base\mpp_buf_slot.cpp_  is looking for _mpp_log.h_, but it crashes since it is not in the same folder. 

So, what is actually the correct way of handling the library files? Where do I place the folders from this API?

**Comment by HermanChen** [comment]
The cmake script handled the include directories by include_directories in CMakeLists.txt

**Comment by Nybon** [comment]
I changed my build system to cmake and here is my CMakeLists.txt file. 
![Capture](https://user-images.githubusercontent.com/64807403/99191242-ba914a80-276b-11eb-8ed8-2cc287861087.PNG)
What should I add to my CMakeLists.txt?

**Comment by HermanChen** [comment]
include_directories(your_directory)

**Comment by Nybon** [comment]
![Capture](https://user-images.githubusercontent.com/64807403/99302739-146b4080-2850-11eb-9d20-f556c97942dc.PNG)
I'm now able to find all the headers, but I am not able to use the functions. What should I write in my CMakeLists.txt to fix this?

**Comment by HermanChen** [comment]
You also need to add more source code.
The mpp_packet is in mpp/base/

**Comment by Nybon** [comment]
This example https://github.com/WainDing/mpp_linux_cpp/blob/master/CMakeLists.txt imports the whole library with target_link_libraries(mpp_linux_demo mpp pthread drm). 

Can I use something similar in my situation?

I added these lines to my CMakeLists.txt file:
include_directories(inc)
include_directories(utils)
include_directories(osal/inc)
include_directories(mpp/inc)
add_subdirectory(mpp)
![Capture](https://user-images.githubusercontent.com/64807403/99398400-a755ba80-28e4-11eb-9a63-0eb863bede56.PNG)

**Comment by HermanChen** [comment]
Yes, it is right.

**Comment by Nybon** [comment]
I am using target_link_libraries(mpp_linux_demo mpp pthread drm).

I have included the following directories:
include_directories(inc)
include_directories(utils)
include_directories(osal/inc)
include_directories(mpp/inc)
include_directories(mpp/hal/inc)
add_subdirectory(mpp)

And I am still getting the error messages shown in the picture above.

**Comment by HermanChen** [comment]
Sub-directory should be also added. The sub-diretory CMakeLists.txt should be recursively included.

**Comment by Nybon** [comment]
I have added:
add_subdirectory(mpp)
add_subdirectory(osal)
add_subdirectory(utils)
add_subdirectory(test)
add_subdirectory(mpp-develop)
add_subdirectory(hal)
add_subdirectory(base)
add_subdirectory(codec)
add_subdirectory(mpp/legacy)
add_subdirectory(mpp/hal)
add_subdirectory(mpp)
add_subdirectory(osal)
add_subdirectory(test)
add_subdirectory(utils)
add_subdirectory(mpp/hal)
add_subdirectory(mpp/base)
add_subdirectory(mpp/codec)
add_subdirectory(mpp/vproc)
add_subdirectory(osal/test)
add_subdirectory(mpp/legacy)
add_subdirectory(mpp/hal/vpu)
add_subdirectory(mpp/codec/rc)
add_subdirectory(mpp/base/test)
add_subdirectory(mpp/codec/dec)
add_subdirectory(mpp/codec/enc)
add_subdirectory(mpp/hal/dummy)
add_subdirectory(mpp/hal/rkenc)
add_subdirectory(mpp/vproc/iep)
add_subdirectory(mpp/vproc/rga)
add_subdirectory(mpp/hal/common)
add_subdirectory(mpp/hal/vpu/common)
add_subdirectory(mpp/vproc/iep/test)

But nothing new happens.

**Comment by HermanChen** [comment]
add_subdirectory is to add the CMakeLists.txt in the subdirectory. Use include_directories also to add include directory.

**Comment by EhsanVahab** [comment]
> I have added: add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(utils) add_subdirectory(test) add_subdirectory(mpp-develop) add_subdirectory(hal) add_subdirectory(base) add_subdirectory(codec) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal) add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(test) add_subdirectory(utils) add_subdirectory(mpp/hal) add_subdirectory(mpp/base) add_subdirectory(mpp/codec) add_subdirectory(mpp/vproc) add_subdirectory(osal/test) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal/vpu) add_subdirectory(mpp/codec/rc) add_subdirectory(mpp/base/test) add_subdirectory(mpp/codec/dec) add_subdirectory(mpp/codec/enc) add_subdirectory(mpp/hal/dummy) add_subdirectory(mpp/hal/rkenc) add_subdirectory(mpp/vproc/iep) add_subdirectory(mpp/vproc/rga) add_subdirectory(mpp/hal/common) add_subdirectory(mpp/hal/vpu/common) add_subdirectory(mpp/vproc/iep/test)
> 
> But nothing new happens.

Dear @Nybon
did you solve the problem?
could you please share your experience?

**Comment by Nybon** [comment]
> > I have added: add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(utils) add_subdirectory(test) add_subdirectory(mpp-develop) add_subdirectory(hal) add_subdirectory(base) add_subdirectory(codec) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal) add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(test) add_subdirectory(utils) add_subdirectory(mpp/hal) add_subdirectory(mpp/base) add_subdirectory(mpp/codec) add_subdirectory(mpp/vproc) add_subdirectory(osal/test) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal/vpu) add_subdirectory(mpp/codec/rc) add_subdirectory(mpp/base/test) add_subdirectory(mpp/codec/dec) add_subdirectory(mpp/codec/enc) add_subdirectory(mpp/hal/dummy) add_subdirectory(mpp/hal/rkenc) add_subdirectory(mpp/vproc/iep) add_subdirectory(mpp/vproc/rga) add_subdirectory(mpp/hal/common) add_subdirectory(mpp/hal/vpu/common) add_subdirectory(mpp/vproc/iep/test)
> > But nothing new happens.
> 
> Dear @Nybon did you solve the problem? could you please share your experience?

I never got it to work, but I found another solution. The project contains samples that will run fine. Try editing the samples instead of building the whole thing from scrath. It may be a bit messy, but it will at least work. Please share a better way to do this if you find one. Remember to keep the same file positions!

**Comment by EhsanVahab** [comment]
> > > I have added: add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(utils) add_subdirectory(test) add_subdirectory(mpp-develop) add_subdirectory(hal) add_subdirectory(base) add_subdirectory(codec) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal) add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(test) add_subdirectory(utils) add_subdirectory(mpp/hal) add_subdirectory(mpp/base) add_subdirectory(mpp/codec) add_subdirectory(mpp/vproc) add_subdirectory(osal/test) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal/vpu) add_subdirectory(mpp/codec/rc) add_subdirectory(mpp/base/test) add_subdirectory(mpp/codec/dec) add_subdirectory(mpp/codec/enc) add_subdirectory(mpp/hal/dummy) add_subdirectory(mpp/hal/rkenc) add_subdirectory(mpp/vproc/iep) add_subdirectory(mpp/vproc/rga) add_subdirectory(mpp/hal/common) add_subdirectory(mpp/hal/vpu/common) add_subdirectory(mpp/vproc/iep/test)
> > > But nothing new happens.
> > 
> > 
> > Dear @Nybon did you solve the problem? could you please share your experience?
> 
> I never got it to work, but I found another solution. The project contains samples that will run fine. Try editing the samples instead of building the whole thing from scrath. It may be a bit messy, but it will at least work. Please share a better way to do this if you find one. Remember to keep the same file positions!

I'm trying to make a simple and clear C++ example.
let you know if I do.

**Comment by EhsanVahab** [comment]
> > > I have added: add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(utils) add_subdirectory(test) add_subdirectory(mpp-develop) add_subdirectory(hal) add_subdirectory(base) add_subdirectory(codec) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal) add_subdirectory(mpp) add_subdirectory(osal) add_subdirectory(test) add_subdirectory(utils) add_subdirectory(mpp/hal) add_subdirectory(mpp/base) add_subdirectory(mpp/codec) add_subdirectory(mpp/vproc) add_subdirectory(osal/test) add_subdirectory(mpp/legacy) add_subdirectory(mpp/hal/vpu) add_subdirectory(mpp/codec/rc) add_subdirectory(mpp/base/test) add_subdirectory(mpp/codec/dec) add_subdirectory(mpp/codec/enc) add_subdirectory(mpp/hal/dummy) add_subdirectory(mpp/hal/rkenc) add_subdirectory(mpp/vproc/iep) add_subdirectory(mpp/vproc/rga) add_subdirectory(mpp/hal/common) add_subdirectory(mpp/hal/vpu/common) add_subdirectory(mpp/vproc/iep/test)
> > > But nothing new happens.
> > 
> > 
> > Dear @Nybon did you solve the problem? could you please share your experience?
> 
> I never got it to work, but I found another solution. The project contains samples that will run fine. Try editing the samples instead of building the whole thing from scrath. It may be a bit messy, but it will at least work. Please share a better way to do this if you find one. Remember to keep the same file positions!

dear @Nybon 
I finally could Make it and use Opencv frame as input frame.
https://github.com/EhsanVahab/rockchip-mpp-encoder
