### ISSUE TITLE
关于图像运动模糊的问题

### ISSUE THREAD

**Issue by caryluck** [HermanChen/mpp#35]
我们现在用mpp编码时遇到一个问题，如果游戏地图场景不移动，画面在整体变化较小情况下解码图像比较清晰，如果整体画面移动时候整体画面明显变模糊。我们现在用的VBR, 尝试过调大bps发现没效果还会是整体画面变卡顿，请问我们改做什么调整能改善这个问题呢？

**Comment by HermanChen** [comment]
用的是什么芯片，能提高码率么？

**Comment by caryluck** [comment]
用的芯片是rk3399，尝试提高过码率画面移动时虽然模糊程度会编好，但帧数明显降低出现卡顿不流畅

**Comment by HermanChen** [comment]
有没有抓一下出现问题的码流场景

**Comment by Meonardo** [comment]
@caryluck @HermanChen 抱歉挖坟, 请问有最终解决方案吗? 

我在 Android 上使用 RK3568 进行 H.264 编码, 编码输入 1920x1080@25fps(NV12), MPP 使用 [tag 1.0.5](https://github.com/HermanChen/mpp/tree/1.0.5), 多媒体库为 GStreamer `1.22.2` 包含 `rockchipmpp`, 我的 gstreamer pipeline 如下:

`... ! mpph264enc rc-mode=cbr header-mode=each-idr bps=4000000 gop=-1 ! ...` 

当输入源场景切换过快(类似于主楼描述), 出现编码模糊甚至延迟增加(解码测观察)现象.
