### ISSUE TITLE
Problems running mpp on RK3328

### ISSUE THREAD

**Issue by Nybon** [HermanChen/mpp#36]
I am having trouble running mpp on RK3328. OS: Ubuntu 18.04.5 LTS. I have been runing different versions of mpp, but no one seems to work in my situation. I have runned some of the examples located in the /test folder. Here is a picture of my results after installing the latest develop branch from this fork and running mpi_test. Here is also an issue I think is related, https://github.com/rockchip-linux/mpp/issues/182.  ![IMG_0020 (2)](https://user-images.githubusercontent.com/64807403/107374779-3fc89900-6ae8-11eb-9a46-fe283f19fbdc.JPG)

**Comment by HermanChen** [comment]
The mpi_test is not maintained. Please use mpi_dec_test and mpi_enc_test.
