### ISSUE TITLE
rk3288 mpp解码jpeg失败

### ISSUE THREAD

**Issue by chong** [HermanChen/mpp#37]
请问kernel版本和mpp版本怎么对应的呢？ kernel 4.4.194，使用最新mpp代码解码jpeg报错，确认是版本兼容问题，这个内核heckout mpp到某个分支正常过，后来再也复现不回去了。

sudo ./test/mpi_dec_test -t 8 -n 1 -f 0   -i ~/test.jpg -w 640 -h 480  -o test.yuv
mpp[1236]: mpi_dec_utils: cmd parse result:
mpp[1236]: mpi_dec_utils: input  file name: /home/firefly/test.jpg
mpp[1236]: mpi_dec_utils: output file name: test.yuv
mpp[1236]: mpi_dec_utils: config file name:
mpp[1236]: mpi_dec_utils: width      :  640
mpp[1236]: mpi_dec_utils: height     :  480
mpp[1236]: mpi_dec_utils: type       : 8
mpp[1236]: mpi_dec_utils: debug flag : 0
mpp[1236]: mpi_dec_utils: max frames : 1
mpp[1236]: mpi_dec_test: mpi_dec_test start
mpp[1236]: mpi_dec_test: input file size 44055
mpp[1236]: mpp_rt: NOT found ion allocator
mpp[1236]: mpp_rt: found drm allocator
mpp[1236]: mpp_info: mpp version: ddcb2785 author: Chen Jinsen   2021-08-19 [jpegd]: Remove stream copy_flag on rk3568
mpp[1236]: mpi_dec_test: 0x80351e60 mpi_dec_test decoder test start w 640 h 480 type 8
mpp[1236]: vcodec_service: vcodec_service_cmd_send ioctl VPU_IOC_SET_REG failed ret -1 errno 14 Bad address
mpp[1236]: HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_start send cmd failed 14
mpp[1236]: vcodec_service: vcodec_service_cmd_poll ioctl VPU_IOC_GET_REG failed ret -1 errno 110 Connection timed out
mpp[1236]: HAL_JPEGD_VDPU1: hal_jpegd_vdpu1_wait poll cmd failed 110
mpp[1236]: mpi_dec_test: 0x80351e60 decoded frame 0
mpp[1236]: mpi_dec_test: 0x80351e60 input 0 pkt output 0 frm decode 0 frames
mpp[1236]: mpi_dec_test: test success max memory 0.00 MB

kernel 日志：
[   49.073777] rk_vcodec: reg_init:1487: error: translate reg address failed, dumping regs
[   49.081867] rk-vcodec ff9a0000.vpu-service: reg[00]: 00000000
[   49.087609] rk-vcodec ff9a0000.vpu-service: reg[01]: 00000001
[   49.093401] rk-vcodec ff9a0000.vpu-service: reg[02]: fff80510
[   49.099152] rk-vcodec ff9a0000.vpu-service: reg[03]: 3000c000
[   49.104979] rk-vcodec ff9a0000.vpu-service: reg[04]: 1400f000
[   49.110765] rk-vcodec ff9a0000.vpu-service: reg[05]: 20001b7c
[   49.116508] rk-vcodec ff9a0000.vpu-service: reg[06]: 00009cff
[   49.122288] rk-vcodec ff9a0000.vpu-service: reg[07]: 0000003f
[   49.128029] rk-vcodec ff9a0000.vpu-service: reg[08]: 00000000
[   49.133796] rk-vcodec ff9a0000.vpu-service: reg[09]: 00000000
[   49.139571] rk-vcodec ff9a0000.vpu-service: reg[10]: 00000000
[   49.145313] rk-vcodec ff9a0000.vpu-service: reg[11]: 00000000
[   49.151084] rk-vcodec ff9a0000.vpu-service: reg[12]: 003c6001
[   49.156837] rk-vcodec ff9a0000.vpu-service: reg[13]: 00000000
[   49.162610] rk-vcodec ff9a0000.vpu-service: reg[14]: 00000000
[   49.168351] rk-vcodec ff9a0000.vpu-service: reg[15]: 00000000
[   49.174103] rk-vcodec ff9a0000.vpu-service: reg[16]: 02031890
[   49.179873] rk-vcodec ff9a0000.vpu-service: reg[17]: 05050304
[   49.185619] rk-vcodec ff9a0000.vpu-service: reg[18]: 00000404
[   49.191380] rk-vcodec ff9a0000.vpu-service: reg[19]: 10907d01
[   49.197126] rk-vcodec ff9a0000.vpu-service: reg[20]: 04030404
[   49.202906] rk-vcodec ff9a0000.vpu-service: reg[21]: 04040507
[   49.208662] rk-vcodec ff9a0000.vpu-service: reg[22]: 77020100
[   49.214408] rk-vcodec ff9a0000.vpu-service: reg[23]: 11111510
[   49.220171] rk-vcodec ff9a0000.vpu-service: reg[24]: 00000001
[   49.225915] rk-vcodec ff9a0000.vpu-service: reg[25]: 11111130
[   49.231674] rk-vcodec ff9a0000.vpu-service: reg[26]: 00000111
[   49.237419] rk-vcodec ff9a0000.vpu-service: reg[27]: 00000000
[   49.243180] rk-vcodec ff9a0000.vpu-service: reg[28]: 00000000
[   49.248940] rk-vcodec ff9a0000.vpu-service: reg[29]: 00000000
[   49.254683] rk-vcodec ff9a0000.vpu-service: reg[30]: 00000000
[   49.260447] rk-vcodec ff9a0000.vpu-service: reg[31]: 00000000
[   49.266191] rk-vcodec ff9a0000.vpu-service: reg[32]: 00000000
[   49.271950] rk-vcodec ff9a0000.vpu-service: reg[33]: 00000000
[   49.277711] rk-vcodec ff9a0000.vpu-service: reg[34]: 00000000
[   49.283456] rk-vcodec ff9a0000.vpu-service: reg[35]: 00000000
[   49.289215] rk-vcodec ff9a0000.vpu-service: reg[36]: 00000000
[   49.294964] rk-vcodec ff9a0000.vpu-service: reg[37]: 00000000
[   49.300727] rk-vcodec ff9a0000.vpu-service: reg[38]: 00000000
[   49.306472] rk-vcodec ff9a0000.vpu-service: reg[39]: 00000000
[   49.312230] rk-vcodec ff9a0000.vpu-service: reg[40]: 00000003
[   49.317994] rk-vcodec ff9a0000.vpu-service: reg[41]: 00000000
[   49.323738] rk-vcodec ff9a0000.vpu-service: reg[42]: 00000000
[   49.329495] rk-vcodec ff9a0000.vpu-service: reg[43]: 00000000
[   49.335240] rk-vcodec ff9a0000.vpu-service: reg[44]: 00000000
[   49.341002] rk-vcodec ff9a0000.vpu-service: reg[45]: 00000000
[   49.346759] rk-vcodec ff9a0000.vpu-service: reg[46]: 00000000
[   49.352504] rk-vcodec ff9a0000.vpu-service: reg[47]: 00000000
[   49.358266] rk-vcodec ff9a0000.vpu-service: reg[48]: 00000000
[   49.364010] rk-vcodec ff9a0000.vpu-service: reg[49]: 00000000
[   49.369776] rk-vcodec ff9a0000.vpu-service: reg[50]: 00000000
[   49.375527] rk-vcodec ff9a0000.vpu-service: reg[51]: 00000000
[   49.381293] rk-vcodec ff9a0000.vpu-service: reg[52]: 00000000
[   49.387054] rk-vcodec ff9a0000.vpu-service: reg[53]: 00000000
[   49.392799] rk-vcodec ff9a0000.vpu-service: reg[54]: 00000000
[   49.398562] rk-vcodec ff9a0000.vpu-service: reg[55]: 00000000
[   49.404306] rk-vcodec ff9a0000.vpu-service: reg[56]: 00000000
[   49.410065] rk-vcodec ff9a0000.vpu-service: reg[57]: 00000000
[   49.415828] rk-vcodec ff9a0000.vpu-service: reg[58]: 00000000
[   49.421572] rk-vcodec ff9a0000.vpu-service: reg[59]: 00000000
[   49.427334] rk-vcodec ff9a0000.vpu-service: reg[60]: 00000002
[   49.433079] rk-vcodec ff9a0000.vpu-service: reg[61]: 0000fef0
[   49.438842] rk-vcodec ff9a0000.vpu-service: reg[62]: 00000000
[   49.444585] rk-vcodec ff9a0000.vpu-service: reg[63]: 00000000
[   49.450344] rk-vcodec ff9a0000.vpu-service: reg[64]: 00000000
[   49.456118] rk-vcodec ff9a0000.vpu-service: reg[65]: 00000000
[   49.461861] rk-vcodec ff9a0000.vpu-service: reg[66]: 00000000
[   49.467623] rk-vcodec ff9a0000.vpu-service: reg[67]: 12c00000
[   49.473372] rk-vcodec ff9a0000.vpu-service: reg[68]: 00000000
[   49.479135] rk-vcodec ff9a0000.vpu-service: reg[69]: 00000000
[   49.484879] rk-vcodec ff9a0000.vpu-service: reg[70]: 00000000
[   49.490641] rk-vcodec ff9a0000.vpu-service: reg[71]: 00001000
[   49.496403] rk-vcodec ff9a0000.vpu-service: reg[72]: 00243c28
[   49.502147] rk-vcodec ff9a0000.vpu-service: reg[73]: 00000000
[   49.507905] rk-vcodec ff9a0000.vpu-service: reg[74]: 00000000
[   49.513652] rk-vcodec ff9a0000.vpu-service: reg[75]: 00000000
[   49.519412] rk-vcodec ff9a0000.vpu-service: reg[76]: 00000000
[   49.525169] rk-vcodec ff9a0000.vpu-service: reg[77]: 00000000
[   49.530914] rk-vcodec ff9a0000.vpu-service: reg[78]: 00000000
[   49.536678] rk-vcodec ff9a0000.vpu-service: reg[79]: 00000000
[   49.542422] rk-vcodec ff9a0000.vpu-service: reg[80]: 00000000
[   49.548180] rk-vcodec ff9a0000.vpu-service: reg[81]: 00000000
[   49.553927] rk-vcodec ff9a0000.vpu-service: reg[82]: 00000000
[   49.559690] rk-vcodec ff9a0000.vpu-service: reg[83]: 00000000
[   49.565448] rk-vcodec ff9a0000.vpu-service: reg[84]: 00000000
[   49.571192] rk-vcodec ff9a0000.vpu-service: reg[85]: 94f02800
[   49.576956] rk-vcodec ff9a0000.vpu-service: reg[86]: 04800000
[   49.582699] rk-vcodec ff9a0000.vpu-service: reg[87]: 00000000
[   49.588462] rk-vcodec ff9a0000.vpu-service: reg[88]: 14000000
[   49.594228] rk-vcodec ff9a0000.vpu-service: reg[89]: 00000000
[   49.599971] rk-vcodec ff9a0000.vpu-service: reg[90]: 00000000
[   49.605728] rk-vcodec ff9a0000.vpu-service: reg[91]: 00000000
[   49.611479] rk-vcodec ff9a0000.vpu-service: reg[92]: 00000280
[   49.617240] rk-vcodec ff9a0000.vpu-service: reg[93]: 00000000
[   49.622984] rk-vcodec ff9a0000.vpu-service: reg[94]: 00000000
[   49.628743] rk-vcodec ff9a0000.vpu-service: reg[95]: 00000000
[   49.634505] rk-vcodec ff9a0000.vpu-service: reg[96]: 00000000
[   49.640250] rk-vcodec ff9a0000.vpu-service: reg[97]: 00000000
[   49.646007] rk-vcodec ff9a0000.vpu-service: reg[98]: 00000000
[   49.651751] rk-vcodec ff9a0000.vpu-service: reg[99]: 00000000
[   49.657512] rk-vcodec ff9a0000.vpu-service: reg[100]: 00000000
[   49.663354] rk-vcodec ff9a0000.vpu-service: reg[101]: 00000000
[   49.669180] rk-vcodec ff9a0000.vpu-service: reg[102]: 00000000
[   49.675026] rk-vcodec ff9a0000.vpu-service: reg[103]: 00000000
[   49.680851] rk-vcodec ff9a0000.vpu-service: reg[104]: 00000000
[   49.686692] rk-vcodec ff9a0000.vpu-service: reg[105]: 00000000
[   49.692521] rk-vcodec ff9a0000.vpu-service: reg[106]: 00000000
[   49.698364] rk-vcodec ff9a0000.vpu-service: reg[107]: 00000000
[   49.704208] rk-vcodec ff9a0000.vpu-service: reg[108]: 00000000
[   49.710035] rk-vcodec ff9a0000.vpu-service: reg[109]: 00000000
[   49.715887] rk-vcodec ff9a0000.vpu-service: reg[110]: 00000000
[   49.721713] rk-vcodec ff9a0000.vpu-service: reg[111]: 00000000
[   49.727555] rk-vcodec ff9a0000.vpu-service: reg[112]: 00000000
[   49.733401] rk-vcodec ff9a0000.vpu-service: reg[113]: 00000000
[   49.739227] rk-vcodec ff9a0000.vpu-service: reg[114]: 00000000
[   49.745066] rk-vcodec ff9a0000.vpu-service: reg[115]: 00000000
[   49.750897] rk-vcodec ff9a0000.vpu-service: reg[116]: 00000000
[   49.756742] rk-vcodec ff9a0000.vpu-service: reg[117]: 00000000
[   49.762582] rk-vcodec ff9a0000.vpu-service: reg[118]: 00000000
[   49.768409] rk-vcodec ff9a0000.vpu-service: reg[119]: 00000000
[   49.774253] rk-vcodec ff9a0000.vpu-service: reg[120]: 00000000
[   49.780079] rk-vcodec ff9a0000.vpu-service: reg[121]: 00000000
[   49.785919] rk-vcodec ff9a0000.vpu-service: reg[122]: 00000000
[   49.791767] rk-vcodec ff9a0000.vpu-service: reg[123]: 00000000
[   49.797592] rk-vcodec ff9a0000.vpu-service: reg[124]: 00000000
[   49.803432] rk-vcodec ff9a0000.vpu-service: reg[125]: 00000000
[   49.809261] rk-vcodec ff9a0000.vpu-service: reg[126]: 00000000
[   49.815104] rk-vcodec ff9a0000.vpu-service: reg[127]: 00000000
[   49.820932] rk-vcodec ff9a0000.vpu-service: reg[128]: 00000000
[   49.826772] rk-vcodec ff9a0000.vpu-service: reg[129]: 00000000
[   49.832617] rk-vcodec ff9a0000.vpu-service: reg[130]: 00000000
[   49.838444] rk-vcodec ff9a0000.vpu-service: reg[131]: 00000000
[   49.844283] rk-vcodec ff9a0000.vpu-service: reg[132]: 00000000
[   49.850112] rk-vcodec ff9a0000.vpu-service: reg[133]: 00000000
[   49.855957] rk-vcodec ff9a0000.vpu-service: reg[134]: 00000000
[   49.861798] rk-vcodec ff9a0000.vpu-service: reg[135]: 00000000
[   49.867624] rk-vcodec ff9a0000.vpu-service: reg[136]: 00000000
[   49.873469] rk-vcodec ff9a0000.vpu-service: reg[137]: 00000000
[   49.879294] rk-vcodec ff9a0000.vpu-service: reg[138]: 00000000
[   49.885134] rk-vcodec ff9a0000.vpu-service: reg[139]: 00000000
[   49.890981] rk-vcodec ff9a0000.vpu-service: reg[140]: 00000000
[   49.896807] rk-vcodec ff9a0000.vpu-service: reg[141]: 00000000
[   49.902645] rk-vcodec ff9a0000.vpu-service: reg[142]: 00000000
[   49.908477] rk-vcodec ff9a0000.vpu-service: reg[143]: 00000000
[   49.914321] rk-vcodec ff9a0000.vpu-service: reg[144]: 00000000
[   49.920165] rk-vcodec ff9a0000.vpu-service: reg[145]: 00000000
[   49.925991] rk-vcodec ff9a0000.vpu-service: reg[146]: 00000000
[   49.931836] rk-vcodec ff9a0000.vpu-service: reg[147]: 00000000
[   49.937662] rk-vcodec ff9a0000.vpu-service: reg[148]: 00000000
[   49.943502] rk-vcodec ff9a0000.vpu-service: reg[149]: 00000000
[   49.949331] rk-vcodec ff9a0000.vpu-service: reg[150]: 00000000
[   49.955174] rk-vcodec ff9a0000.vpu-service: reg[151]: 00000000
[   49.961014] rk-vcodec ff9a0000.vpu-service: reg[152]: 00000000
[   49.966840] rk-vcodec ff9a0000.vpu-service: reg[153]: 00000000
[   49.972690] rk-vcodec ff9a0000.vpu-service: reg[154]: 00000000
[   49.978516] rk-vcodec ff9a0000.vpu-service: reg[155]: 00000000
[   49.984360] rk-vcodec ff9a0000.vpu-service: reg[156]: 00000000
[   49.990206] rk-vcodec ff9a0000.vpu-service: reg[157]: 00000000
[   49.996032] rk-vcodec ff9a0000.vpu-service: reg[158]: 00000000
[   50.001872] rk-vcodec ff9a0000.vpu-service: reg[159]: 00000000
[   50.007701] rk-vcodec ff9a0000.vpu-service: reg[160]: 00000000
[   50.013545] rk-vcodec ff9a0000.vpu-service: reg[161]: 00000000
[   50.019385] rk-vcodec ff9a0000.vpu-service: reg[162]: 00000000
[   50.025211] rk-vcodec ff9a0000.vpu-service: reg[163]: 00000000

**Comment by HermanChen** [comment]
内核日志有更完整一些么

**Comment by chong** [comment]
解决了，编译加入参数-DHAVE_DRM=1
