### ISSUE TITLE
How to enable OSD

### ISSUE THREAD

**Issue by Dex-Hacker** [HermanChen/mpp#38]
在编码时加上 osd_enable=1 ./mpi_enc_test
编码后的图片没有出现任何反应正常吗?
RK3399

**Comment by HermanChen** [comment]
osd_enable=1 这个在 3399 上没用……
编码器的 osd 支持是从 1126/1109/3568/3566 这些的新芯片上才开始支持的，有 rkvenc 编码器硬件的芯片

**Comment by Dex-Hacker** [comment]
solved，tks
