### ISSUE TITLE
jpeg 解码出错HAL_JPEG_VDPU2: hal_jpegd_vdpu2_wait IRQ STREAM ERROR!

### ISSUE THREAD

**Issue by huangxxpp** [HermanChen/mpp#40]
运行命令解码input13.jpeg，mpi_dec_test -i input13.jpeg -t 8 -o t3.yuv -w 1920 -h 1080
提示错误:HAL_JPEG_VDPU2: hal_jpegd_vdpu2_wait IRQ STREAM ERROR!
[input13.jpeg.zip](https://github.com/HermanChen/mpp/files/8221722/input13.jpeg.zip)

**Comment by huangxxpp** [comment]
这个jpeg文件是从蓝色妖姬的USB摄像头拿到的

**Comment by huangxxpp** [comment]
解码出来的yuv文件也不正常

**Comment by VicLiDev** [comment]
你好，是哪一个硬件平台上的问题？
查看输出的yuv时，格式有正确配置吗？可以试一下 422 8bit 是否可以正常显示
