### ISSUE TITLE
RK3568 mpp decode h264 failed

### ISSUE THREAD

**Issue by 1891er** [HermanChen/mpp#41]
在Rock pi 3A(RK3568)上，跑 mpp_dec_test 失败，提示：
mpp[39110]: vcodec_service: open vcodec_service /dev/mpp_service failed
存在/dev/mpp_service设备节点，请问是什么原因呢？

rock@rock-3a:~/work/test$ ./mpi_dec_test -t 7 -w 1920 -h 1080 -i ~/work/test_1080.264
mpp[39110]: mpp_opt: setup:real node 18:22 info 11:11
mpp[39110]: mpi_dec_utils: input file /home/rock/work/test_1080.264 size 98864264
mpp[39110]: mpi_dec_utils: cmd parse result:
mpp[39110]: mpi_dec_utils: input  file name: /home/rock/work/test_1080.264
mpp[39110]: mpi_dec_utils: output file name: 
mpp[39110]: mpi_dec_utils: width      : 1920
mpp[39110]: mpi_dec_utils: height     : 1080
mpp[39110]: mpi_dec_utils: type       :    7
mpp[39110]: mpi_dec_utils: max frames :    0
mpp[39110]: mpi_dec_test: mpi_dec_test start
mpp[39110]: mpp_info: mpp version: 8a85dc5d author: Herman Chen   2022-03-14 [mpp_enc]: Fix stuck on reset async mode encoder
mpp[39110]: mpi_dec_test: 0x55ad428860 mpi_dec_test decoder test start w 1920 h 1080 type 7
mpp[39110]: mpp_rt: NOT found ion allocator
mpp[39110]: mpp_rt: found drm allocator
**mpp[39110]: vcodec_service: open vcodec_service /dev/mpp_service failed**
mpp[39110]: hal_h264d_api: mpp_dev_init failed ret: -1
mpp[39110]: mpp_hal: mpp_hal_init hal h264d_rkdec init failed ret -1
mpp[39110]: mpp_hal: mpp_hal_init could not found coding type 7
mpp[39110]: mpp_dec: mpp_dec_init could not init hal
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp_time: mpp_clock_put invalid clock (nil)
mpp[39110]: mpp: error found on mpp initialization
mpp[39110]: mpi_dec_test: 0x55ad428860 mpp_init failed
mpp[39110]: mpi_dec_test: test failed ret -1
mpi_dec_test[39110]: mpp_mem_pool: put_pool found 1 used buffer size 80
mpi_dec_test[39110]: mpp_mem_pool: put_pool found 4 used buffer size 192
rock@rock-3a:~/work/test$

**Comment by HermanChen** [comment]
设备权限，先 su 切到 root
