### ISSUE TITLE
[h264e_vepu580]: Add dpb hal func and more buffer]实现也应该同时实现h264e_vepu541

### ISSUE THREAD

**Issue by jiale-gdyd** [HermanChen/mpp#42]
[[h264e_vepu580]: Add dpb hal func and more buffer](https://github.com/Caesar-github/mpp/commit/f0079f49d247288631aa42e83e20f7b2d456f2f6)
这一个实现也应该在h264e_vepu541上面类似实现，不然在rv1126上update_vepu541_syntax函数会执行default条件了，就会一直打印mpp_log_f("invalid syntax type %d\n", desc->type);

**Comment by HermanChen** [comment]
收到，多谢

**Comment by jiale-gdyd** [comment]
![image](https://user-images.githubusercontent.com/65750284/162388049-5e740194-c210-4f49-8c0a-ee8f0f3f6eb3.png)
![image](https://user-images.githubusercontent.com/65750284/162388136-3364f1c5-09a6-4d60-91aa-12e7e45d06ca.png)
请问这两处不用加上吗？

**Comment by jiale-gdyd** [comment]
![image](https://user-images.githubusercontent.com/65750284/162388693-587d70ba-a0f1-499b-a3cc-0efe2e9396db.png)
还有这里

**Comment by jiale-gdyd** [comment]
![image](https://user-images.githubusercontent.com/65750284/162392602-a05fe74d-c5f2-48d7-9e92-45f23ef07eb7.png)

**Comment by HermanChen** [comment]
因为这个 dpb 只有 vepu580 的 h264 会用到，其他的编码器不会用到，这个是用来处理多帧多核并行编码问题的，其他器件没有这个需求
