### ISSUE TITLE
Build mpp, and gets Segmentation Fault

### ISSUE THREAD

**Issue by Wazirri** [HermanChen/mpp#47]
I build @HermanChen mpp/build/linux/aarch64.

and install mpp/debian librockchip-mpp-dev.install, librockchip-mpp1.install, rockchip-mpp-demos.install, librockchip-vpu0.install

If I give all parameters it gives Seg fault

root@radxa-cm3-io:/home/rock# mpi_dec_test  demo.h264 -w 10 -h 10 -t 7 
Segmentation fault

if I do not give -t 7 parameters

root@radxa-cm3-io:/home/rock# mpi_dec_test 2022-06-18_15-15-54.mkv -w 10 -h 10     
root@radxa-cm3-io:/home/rock# 

It does not give any output

**Comment by HermanChen** [comment]
mpi_dec_test -i demo.h264 即可

**Comment by Wazirri** [comment]
Sorry, it is working now. With your MPP build.

Now it gives such warning. Can you also help? Thanks



![image](https://user-images.githubusercontent.com/59524403/182956681-2511db3f-f283-41df-a956-bfb7f0148611.png)



![image](https://user-images.githubusercontent.com/59524403/182956564-089f9748-2fae-47ac-9a36-b7902aede2c1.png)

**Comment by HermanChen** [comment]
The warning is about the deprecated old timeout control

**Comment by HermanChen** [comment]
It is just ok
