### ISSUE TITLE
void os_log_error(const char* tag, const char* msg, va_list list)会崩

### ISSUE THREAD

**Issue by jiale-gdyd** [HermanChen/mpp#55]
![image](https://user-images.githubusercontent.com/65750284/222320749-b46564b0-a7fa-4b63-9a6e-fecfdcb071eb.png)

**Comment by HermanChen** [comment]
看下为啥崩，是输入什么了

**Comment by jiale-gdyd** [comment]
就是在我把所有的HAVE_H264D， HAVE_XXX这些全部不开启，然后调用解码接口去解码，然后就崩了，os_log_info(debug, trace)这些也会崩。然后我就怀疑里面的参数是不是不对，我直接在里面调用printf去打印，发现也崩了，应该就是传入到这些接口的参数有问题

**Comment by HermanChen** [comment]
有个 mpp_log_test 测试用例，跑一下看看~
