### ISSUE TITLE
如何绑定纹理指针,让MPP解码直接将数据赋值给纹理指针? 

### ISSUE THREAD

**Issue by lion117** [HermanChen/mpp#60]
# 背景
解码后获取CPU的NV12S数据, 再映射到纹理进行渲染. 这个流程比较耗时, 耗性能. 

# 要求
希望能否像android 的mediacodec, 直接将纹理指针传给解码器, 解码后直接渲染数据. 

# 期望
1. 是否支持类似的功能
2. 能否提供相关的demo 用法

**Comment by HermanChen** [comment]
可以，正常解码器的流程就是使用 native window galloc 分配出来的 buffer 的。
gpu 的驱动是可以支持导入 dma buf 的

**Comment by HermanChen** [comment]
参考下这里
https://github.com/JeffyCN/drm-cursor/blob/master/drm_egl.c#L402
