### ISSUE TITLE
RK3588在1080p下的最大编码帧率是多少？

### ISSUE THREAD

**Issue by bravomikekilo** [HermanChen/mpp#62]
RK3588 按照说明支持8k@30fps, 但是更低分辨率的编码帧率没有说明, 问一下RK3588在1080p的最大编码帧率是多少啊? 我们这边的潜在应用需要实时高帧率编码视频, VP8, H.264/H.265都可以, 目前有最大帧率的测试数据吗?

**Comment by HermanChen** [comment]
按分辨率换算，8K = 4 * 4K = 16 * 1080p，所以 8K 30fps = 4K 120fps = 1080p 480fps
vp8 只有 1080p@30fps 的能力，不高
这个能力我们有测试过，基本能等价换算
