### ISSUE TITLE
1920*1080大小输入图像帧拷贝到mpp frame buffer占用CPU高

### ISSUE THREAD

**Issue by Iyiren** [HermanChen/mpp#64]
我在使用XDMA从FPGA PCIE把数据放到了xdma.buffer里，xdma.buffer是posix_memalign()分配的内存，当我把1920*1080*3大小的数据用memcpy拷贝到mpp buffer(DRM或者DMA_HEAP类型)里，使用时间3---4ms，但是cpu占用率约40%。
我又使用librga的imcopy()，效果差不多，耗时3---4ms，cpu占用率仍然30%~40%。
请问有没有什么方法可以降低CPU使用率呢？有没有免拷贝或者DMA直接拷贝，不经过CPU的方法呢？

**Comment by HermanChen** [comment]
能直接写到 MppBuffer 对应 fd 的 dmabuf 里么？不要用 malloc 出来的内存
