### ISSUE TITLE
H264最大的nal size限制无效

### ISSUE THREAD

**Issue by xb985547608** [HermanChen/mpp#65]
我需要控制每个nal的大小在1500以下，在256bps的码率下，nal的大小可以保证都在1500以下，但是我将码率调整到512bps后，部分nal大小将超过了1500，请问我该如何做才能保证在任何码率下都可以确保nal的大小不超过1500

mpp_enc_cfg_set_u32(d->cfg, "split:mode", MPP_ENC_SPLIT_BY_BYTE);
mpp_enc_cfg_set_u32(d->cfg, "split:arg", 1480);

硬件平台：rk3128
编码大小：640*480
mpp_info: mpp version: https://github.com/rockchip-linux/mpp/commit/0b5a25d9035e26338eb60a25b26d9b5c2a049e10 author: Herman Chen 2020-07-24 [utils]: Fix encoder width / stride mismatch

**Comment by HermanChen** [comment]
更新下 develop 分支的代码试一下，不超过 1500 的话，可以配置得更小一些，比如 1200
