### ISSUE TITLE
H.265 Encoding Not Supported

### ISSUE THREAD

**Issue by jbloomfield2008** [HermanChen/mpp#7]
The MPP library currently only support hardware encoding for H.264, yet the RK3328 support both H.264 and H.265.

**Comment by HermanChen** [comment]
H.265 encoder driver is under developing. It will come soon.

**Comment by jbloomfield2008** [comment]
If you need any beta testers let me know, I'll be happy to test.

**Comment by HermanChen** [comment]
The RK3328 will not support H.265 encoding at mpp.
You can try RV1109/RV1126/RK3566/RK3568

**Comment by DurvalMenezes** [comment]
That's quite a disappointment, specially after waiting for ~3 years while it was supposedly "under developing". X.265 hardware encoding is essential for my use case (and I suspect,  many other people's).

Are you with RocketChip? If you are, please let the bosses know we will be thinking thrice before investing money/time/mindshare in RocketChip products in the future.

**Comment by HermanChen** [comment]
> 
> 
> That's quite a disappointment, specially after waiting for ~3 years while it was supposedly "under developing". X.265 hardware encoding is essential for my use case (and I suspect, many other people's).
> 
> Are you with RocketChip? If you are, please let the bosses know we will be thinking thrice before investing money/time/mindshare in RocketChip products in the future.

The H.265 encoder on RK3328 is mainly for operator requirement and it works only on dedicated 4.4 kernel in operator SDK for set top box.
So it is supported with hal/vepu22 in mpp. You can find it is quite a uncommon hardware encoder.
With special kernel and SDK the vepu22 can run properly on RK3328.

Then kernel update to 4.19 and our own next generation hardware encoder on RV1109/RV1126/RK3566/RK3568 is ready.
To support the special hardware with special kernel on latest MPP is meanless. So it is removed from the latest encoder framework. But the vepu22 code is still there for reference.

If you really need the H.265 hardware encoder on RK3328 so badly please send your requirement to our FAE and ask for the dedicated SDK.

Note: The compression rate of H.265 encoder on RK3328 is only a half of the one on RV1126. It is even not better than the H.264 encoder on RV1108. So turn to new choice is better for your product and your customer.

**Comment by landswellsong** [comment]
@HermanChen is there a way to obtain this dedicated SDK or an image to test the VEPU22 in action?
I'm thinking of forwardporting the old VEPU22 code for the modern mpp API myself, but I wanted to have a stable point of reference as a benchmark.
